name: nexus
channels:
  - pytorch
  - conda-forge
  - defaults

dependencies:
  - python=3.9
  - pytorch>=1.12.0  # CPU/MPS for macOS
  - torchvision>=0.13.0
  - torchaudio>=0.12.0
  - numpy>=1.21.0
  - scipy>=1.7.0
  - matplotlib>=3.5.0
  - seaborn>=0.11.0
  - pillow>=8.3.0
  - pytest>=7.0.0
  - black>=22.0.0
  - flake8>=4.0.0
  - mypy>=0.950
  - jupyter
  - ipykernel
  - pyyaml>=6.0
  - tqdm>=4.64.0
  - imageio>=2.19.0
  - pip
  - pip:
    - gymnasium>=0.26.0
    - stable-baselines3>=1.7.0
    - wandb>=0.13.0
    - tensorboard>=2.8.0
    - ray[default]>=2.0.0
    - moviepy>=1.0.3
